/**
 * @tsports/gamut - Color generation
 *
 * Ported from generator.go
 */

import { type Color, Lab, MakeColor } from '@tsports/go-colorful';
import { KMeans } from './utils/kmeans.js';

export interface ColorGenerator {
  valid(col: Color): boolean;
  granularity(): [number, number]; // returns [l, c]
}

export class BroadGranularity {
  granularity(): [number, number] {
    return [0.05, 0.1];
  }
}

export class FineGranularity {
  granularity(): [number, number] {
    return [0.01, 0.01];
  }
}

function distanceDegrees(a1: number, a2: number): number {
  const mod = Math.abs(a1 - a2) % 360.0;
  if (mod > 180.0) {
    return 360.0 - mod;
  }
  return mod;
}

export class SimilarHueGenerator extends FineGranularity implements ColorGenerator {
  color: Color;

  constructor(c: Color) {
    super();
    this.color = c;
  }

  valid(col: Color): boolean {
    const [cf] = MakeColor(this.color);
    const [h, c, l] = cf.hcl();
    const [hc, cc, lc] = col.hcl();

    if (cc < c - 0.35 || cc > c + 0.35) {
      return false;
    }
    if (lc < l - 0.6 || lc > l + 0.6) {
      return false;
    }
    if (distanceDegrees(h, hc) > 7) {
      return false;
    }
    if (cf.distanceCIE94(col) > 0.2) {
      return false;
    }

    return true;
  }
}

export class WarmGenerator extends BroadGranularity implements ColorGenerator {
  valid(col: Color): boolean {
    const [, c, l] = col.hcl();
    return 0.1 <= c && c <= 0.4 && 0.2 <= l && l <= 0.5;
  }
}

export class HappyGenerator extends BroadGranularity implements ColorGenerator {
  valid(col: Color): boolean {
    const [, c, l] = col.hcl();
    return 0.3 <= c && 0.4 <= l && l <= 0.8;
  }
}

export class PastelGenerator extends BroadGranularity implements ColorGenerator {
  valid(col: Color): boolean {
    const [, s, v] = col.hsv();
    return 0.2 <= s && s <= 0.4 && 0.7 <= v && v <= 1.0;
  }
}

/**
 * generate returns a slice with the requested amount of colors, generated by
 * the provided ColorGenerator.
 * Returns [colors, error] tuple for Go compatibility.
 */
export function generate(count: number, generator: ColorGenerator): [Color[], Error | null] {
  const [dl, dab] = generator.granularity();
  const d: [number, number, number][] = []; // Points in Lab space

  for (let l = 0.0; l <= 1.0; l += dl) {
    for (let a = -1.0; a < 1.0; a += dab) {
      for (let b = -1.0; b < 1.0; b += dab) {
        const col = Lab(l, a, b);

        if (!col.isValid() || !generator.valid(col)) {
          continue;
        }

        const [labL, labA, labB] = col.lab();
        d.push([labL, labA, labB]);
      }
    }
  }

  // Use KMeans clustering
  const kmeans = new KMeans(count, d);
  const clusters = kmeans.run(); // returns centroids

  const cc: Color[] = [];
  for (const c of clusters) {
    const col = Lab(c[0], c[1], c[2]).clamped();
    cc.push(col);
  }

  return [cc, null];
}
