$schema: "https://moonrepo.dev/schemas/tasks.json"

implicitDeps:
  - "^:build"

implicitInputs:
  - "tsconfig.*.json"

fileGroups:
  # Angular specific files
  app:
    - "src/main.ts"
    - "src/index.html"
  configs:
    - "*.{js,json,yml,yaml}"
    - "tsconfig.*.json"
  sources:
    - "src/**/*"
    - "public/**/*"
  tests:
    - "src/**/*.spec.ts"
    - "src/**/*.test.ts"
    - "src/test.ts"
  styles:
    - "src/**/*.{scss,css,sass,less}"
    - "src/styles.scss"

tasks:
  build:
    command: "ng build rbx"
    inputs:
      - "@group(app)"
      - "@globs(sources)"
      - "@globs(styles)"
      - "@globs(configs)"
    outputs:
      - dist
    options:
      cache: false
      merge: replace