import { hex } from '../colors.js';
import { Palette } from '../palette.js';

export const CSS = new Palette();

// https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
CSS.addColors([
  // CSS Level 1
  { name: 'black', color: hex('#000000'), reference: '' },
  { name: 'silver', color: hex('silver'), reference: '' },
  { name: 'gray', color: hex('#808080'), reference: '' },
  { name: 'white', color: hex('#ffffff'), reference: '' },
  { name: 'maroon', color: hex('#800000'), reference: '' },
  { name: 'red', color: hex('#ff0000'), reference: '' },
  { name: 'purple', color: hex('#800080'), reference: '' },
  { name: 'fuchsia', color: hex('#ff00ff'), reference: '' },
  { name: 'green', color: hex('#008000'), reference: '' },
  { name: 'lime', color: hex('#00ff00'), reference: '' },
  { name: 'olive', color: hex('#808000'), reference: '' },
  { name: 'yellow', color: hex('#ffff00'), reference: '' },
  { name: 'navy', color: hex('#000080'), reference: '' },
  { name: 'blue', color: hex('#0000ff'), reference: '' },
  { name: 'teal', color: hex('#008080'), reference: '' },
  { name: 'aqua', color: hex('#00ffff'), reference: '' },

  // CSS Level 2 (Revision 1)
  { name: 'orange', color: hex('#ffa500'), reference: '' },

  // CSS Color Module Level 3
  { name: 'aliceblue', color: hex('#f0f8ff'), reference: '' },
  { name: 'antiquewhite', color: hex('#faebd7'), reference: '' },
  { name: 'aquamarine', color: hex('#7fffd4'), reference: '' },
  { name: 'azure', color: hex('#f0ffff'), reference: '' },
  { name: 'beige', color: hex('#f5f5dc'), reference: '' },
  { name: 'bisque', color: hex('#ffe4c4'), reference: '' },
  { name: 'blanchedalmond', color: hex('#ffebcd'), reference: '' },
  { name: 'blueviolet', color: hex('#8a2be2'), reference: '' },
  { name: 'brown', color: hex('#a52a2a'), reference: '' },
  { name: 'burlywood', color: hex('#deb887'), reference: '' },
  { name: 'cadetblue', color: hex('#5f9ea0'), reference: '' },
  { name: 'chartreuse', color: hex('#7fff00'), reference: '' },
  { name: 'chocolate', color: hex('#d2691e'), reference: '' },
  { name: 'coral', color: hex('#ff7f50'), reference: '' },
  { name: 'cornflowerblue', color: hex('#6495ed'), reference: '' },
  { name: 'cornsilk', color: hex('#fff8dc'), reference: '' },
  { name: 'crimson', color: hex('#dc143c'), reference: '' },
  { name: 'cyan', color: hex('#00ffff'), reference: '' }, // not: synonym of aqua
  { name: 'darkblue', color: hex('#00008b'), reference: '' },
  { name: 'darkcyan', color: hex('#008b8b'), reference: '' },
  { name: 'darkgoldenrod', color: hex('#b8860b'), reference: '' },
  { name: 'darkgray', color: hex('#a9a9a9'), reference: '' },
  { name: 'darkgreen', color: hex('#006400'), reference: '' },
  { name: 'darkgrey', color: hex('#a9a9a9'), reference: '' },
  { name: 'darkkhaki', color: hex('#bdb76b'), reference: '' },
  { name: 'darkmagenta', color: hex('#8b008b'), reference: '' },
  { name: 'darkolivegreen', color: hex('#556b2f'), reference: '' },
  { name: 'darkorange', color: hex('#ff8c00'), reference: '' },
  { name: 'darkorchid', color: hex('#9932cc'), reference: '' },
  { name: 'darkred', color: hex('#8b0000'), reference: '' },
  { name: 'darksalmon', color: hex('#e9967a'), reference: '' },
  { name: 'darkseagreen', color: hex('#8fbc8f'), reference: '' },
  { name: 'darkslateblue', color: hex('#483d8b'), reference: '' },
  { name: 'darkslategray', color: hex('#2f4f4f'), reference: '' },
  { name: 'darkturquoise', color: hex('#00ced1'), reference: '' },
  { name: 'darkviolet', color: hex('#9400d3'), reference: '' },
  { name: 'deeppink', color: hex('#ff1493'), reference: '' },
  { name: 'deepskyblue', color: hex('#00bfff'), reference: '' },
  { name: 'dimgray', color: hex('#696969'), reference: '' },
  { name: 'dimgrey', color: hex('#696969'), reference: '' }, // note: synonym of dimgray
  { name: 'dodgerblue', color: hex('#1e90ff'), reference: '' },
  { name: 'firebrick', color: hex('#b22222'), reference: '' },
  { name: 'floralwhite', color: hex('#fffaf0'), reference: '' },
  { name: 'forestgreen', color: hex('#228b22'), reference: '' },
  { name: 'gainsboro', color: hex('#dcdcdc'), reference: '' },
  { name: 'ghostwhite', color: hex('#f8f8ff'), reference: '' },
  { name: 'gold', color: hex('#ffd700'), reference: '' },
  { name: 'goldenrod', color: hex('#daa520'), reference: '' },
  { name: 'greenyellow', color: hex('#adff2f'), reference: '' },
  { name: 'grey', color: hex('#808080'), reference: '' },
  { name: 'honeydew', color: hex('#f0fff0'), reference: '' },
  { name: 'hotpink', color: hex('#ff69b4'), reference: '' },
  { name: 'indianred', color: hex('#cd5c5c'), reference: '' },
  { name: 'indigo', color: hex('#4b0082'), reference: '' },
  { name: 'ivory', color: hex('#fffff0'), reference: '' },
  { name: 'khaki', color: hex('#f0e68c'), reference: '' },
  { name: 'lavender', color: hex('#e6e6fa'), reference: '' },
  { name: 'lavenderblush', color: hex('#fff0f5'), reference: '' },
  { name: 'lawngreen', color: hex('#7cfc00'), reference: '' },
  { name: 'lemonchiffon', color: hex('#fffacd'), reference: '' },
  { name: 'lightblue', color: hex('#add8e6'), reference: '' },
  { name: 'lightcoral', color: hex('#f08080'), reference: '' },
  { name: 'lightcyan', color: hex('#e0ffff'), reference: '' },
  { name: 'lightgoldenrodyellow', color: hex('#fafad2'), reference: '' },
  { name: 'lightgray', color: hex('#d3d3d3'), reference: '' },
  { name: 'lightgrey', color: hex('#d3d3d3'), reference: '' }, // note: synonym of lightgray
  { name: 'lightgreen', color: hex('#90ee90'), reference: '' },
  { name: 'lightgrey', color: hex('#d3d3d3'), reference: '' },
  { name: 'lightpink', color: hex('#ffb6c1'), reference: '' },
  { name: 'lightsalmon', color: hex('#ffa07a'), reference: '' },
  { name: 'lightseagreen', color: hex('#20b2aa'), reference: '' },
  { name: 'lightskyblue', color: hex('#87cefa'), reference: '' },
  { name: 'lightslategray', color: hex('#778899'), reference: '' },
  { name: 'lightslategrey', color: hex('#778899'), reference: '' }, // note: synonym of lightslategray
  { name: 'lightsteelblue', color: hex('#b0c4de'), reference: '' },
  { name: 'lightyellow', color: hex('#ffffe0'), reference: '' },
  { name: 'limegreen', color: hex('#32cd32'), reference: '' },
  { name: 'linen', color: hex('#faf0e6'), reference: '' },
  { name: 'magenta', color: hex('#ff00ff'), reference: '' }, // note: synonym of fuchsia
  { name: 'mediumaquamarine', color: hex('#66cdaa'), reference: '' },
  { name: 'mediumblue', color: hex('#0000cd'), reference: '' },
  { name: 'mediumorchid', color: hex('#ba55d3'), reference: '' },
  { name: 'mediumpurple', color: hex('#9370db'), reference: '' },
  { name: 'mediumseagreen', color: hex('#3cb371'), reference: '' },
  { name: 'mediumslateblue', color: hex('#7b68ee'), reference: '' },
  { name: 'mediumspringgreen', color: hex('#00fa9a'), reference: '' },
  { name: 'mediumturquoise', color: hex('#48d1cc'), reference: '' },
  { name: 'mediumvioletred', color: hex('#c71585'), reference: '' },
  { name: 'midnightblue', color: hex('#191970'), reference: '' },
  { name: 'mintcream', color: hex('#f5fffa'), reference: '' },
  { name: 'mistyrose', color: hex('#ffe4e1'), reference: '' },
  { name: 'moccasin', color: hex('#ffe4b5'), reference: '' },
  { name: 'navajowhite', color: hex('#ffdead'), reference: '' },
  { name: 'oldlace', color: hex('#fdf5e6'), reference: '' },
  { name: 'olivedrab', color: hex('#6b8e23'), reference: '' },
  { name: 'orangered', color: hex('#ff4500'), reference: '' },
  { name: 'orchid', color: hex('#da70d6'), reference: '' },
  { name: 'palegoldenrod', color: hex('#eee8aa'), reference: '' },
  { name: 'palegreen', color: hex('#98fb98'), reference: '' },
  { name: 'paleturquoise', color: hex('#afeeee'), reference: '' },
  { name: 'palevioletred', color: hex('#db7093'), reference: '' },
  { name: 'papayawhip', color: hex('#ffefd5'), reference: '' },
  { name: 'peachpuff', color: hex('#ffdab9'), reference: '' },
  { name: 'peru', color: hex('#cd853f'), reference: '' },
  { name: 'pink', color: hex('#ffc0cb'), reference: '' },
  { name: 'plum', color: hex('#dda0dd'), reference: '' },
  { name: 'powderblue', color: hex('#b0e0e6'), reference: '' },
  { name: 'rosybrown', color: hex('#bc8f8f'), reference: '' },
  { name: 'royalblue', color: hex('#4169e1'), reference: '' },
  { name: 'saddlebrown', color: hex('#8b4513'), reference: '' },
  { name: 'salmon', color: hex('#fa8072'), reference: '' },
  { name: 'sandybrown', color: hex('#f4a460'), reference: '' },
  { name: 'seagreen', color: hex('#2e8b57'), reference: '' },
  { name: 'seashell', color: hex('#fff5ee'), reference: '' },
  { name: 'sienna', color: hex('#a0522d'), reference: '' },
  { name: 'skyblue', color: hex('#87ceeb'), reference: '' },
  { name: 'slateblue', color: hex('#6a5acd'), reference: '' },
  { name: 'slategray', color: hex('#708090'), reference: '' },
  { name: 'slategrey', color: hex('#708090'), reference: '' }, // note: synonym of slategray
  { name: 'snow', color: hex('#fffafa'), reference: '' },
  { name: 'springgreen', color: hex('#00ff7f'), reference: '' },
  { name: 'steelblue', color: hex('#4682b4'), reference: '' },
  { name: 'tan', color: hex('#d2b48c'), reference: '' },
  { name: 'thistle', color: hex('#d8bfd8'), reference: '' },
  { name: 'tomato', color: hex('#ff6347'), reference: '' },
  { name: 'turquoise', color: hex('#40e0d0'), reference: '' },
  { name: 'violet', color: hex('#ee82ee'), reference: '' },
  { name: 'wheat', color: hex('#f5deb3'), reference: '' },
  { name: 'whitesmoke', color: hex('#f5f5f5'), reference: '' },
  { name: 'yellowgreen', color: hex('#9acd32'), reference: '' },

  // CSS Color Module Level 4
  // https://en.wikipedia.org/wiki/Eric_A._Meyer#Personal_life
  { name: 'rebeccapurple', color: hex('#663399'), reference: '' },
]);
